# Generated by Django 3.0.3 on 2020-02-07 04:46
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor
from django.db.models.fields.related import *
from django.apps.registry import Apps
from django.db.models.fields import *
from django.db.migrations import *
from django.conf import settings
from decimal import Decimal


class Migration(Migration):

    initial = True
    dependencies = []
    operations = [
        CreateModel(
            name = 'Advertisement',
            fields = [
                ('id', AutoField(null = False, blank = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('title', CharField(null = False, blank = False, max_length = 512, verbose_name = 'advertisement title')),
                ('category', CharField(null = False, blank = False, max_length = 16, choices = [('category-a', 'A-class'), ('category-aa', 'AA-class'), ('category-aaa', 'AAA-class')], verbose_name = 'advertisement category')),
                ('thumbnail', URLField(null = False, blank = False, max_length = 256, verbose_name = 'advertisement thumbnail', help_text = 'This should contain a URL to a thumbnail. URLs must be absolute; to access local resources, use full path.')),
                ('latitude', DecimalField(null = False, blank = False, decimal_places = 6, max_digits = 12, verbose_name = 'latitude')),
                ('longitude', DecimalField(null = False, blank = False, decimal_places = 6, max_digits = 12, verbose_name = 'latitude')),
            ],
            options = { 'verbose_name': 'advertisement', 'verbose_name_plural': 'advertisements', },
        ),
        CreateModel(
            name = 'Gallery',
            fields = [
                ('id', AutoField(null = False, blank = False, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('description', CharField(null = False, blank = False, max_length = 1024, verbose_name = 'description')),
                ('advertisement', OneToOneField('app.Advertisement', null = False, blank = False, on_delete = CASCADE, related_name = 'gallery', related_query_name = 'gallery', verbose_name = 'advertisement')),
                ('interactive_map', URLField(null = False, blank = False, max_length = 256, verbose_name = 'interactive map URL', help_text = 'Prefer shortened URLS for ease of maintenance.')),
            ],
            options = { 'verbose_name': 'gallery', 'verbose_name_plural': 'galleries', },
        ),
        CreateModel(
            name = 'Picture',
            fields = [
                ('id', AutoField(null = False, blank = False, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('front', URLField(null = False, blank = False, max_length = 256, verbose_name = 'picture asset (front)', help_text = 'This should contain a URL to a picture asset. URLs must be absolute; to access local resources, use full path.')),
                ('cross', URLField(null = False, blank = False, max_length = 256, verbose_name = 'picture asset (cross)', help_text = 'This should contain a URL to a picture asset. URLs must be absolute; to access local resources, use full path.')),
                ('gallery', ForeignKey('app.Gallery', null = False, blank = False, on_delete = CASCADE, related_name = 'pictures', related_query_name = 'pictures', verbose_name = 'advertisement')),
            ],
            options = { 'verbose_name': 'advertisement picture', 'verbose_name_plural': 'advertisement pictures', },
        ),
    ]
